root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[dev]
cmd = "go run cmd/main.go"
bin = "tmp/main"

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = false

[proxy]
  app_port = 0
  enabled = false
  proxy_port = 0

[screen]
  clear_on_rebuild = false
  keep_scroll = true
